sonar.projectKey=faustine-cicd-tasklist-frontend

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.ts,src/__tests__/**/*.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info